# Codemagic configuration file for Flutter project
workflows:
  build-movie-tv-series:
    name: Build Movie TV Series
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    environment:
      flutter: 3.27.2
      xcode: latest
      groups:
        - prod
    scripts:
      - name: Create .env file
        script: |
          echo "API_KEY=$API_KEY" > .env
          echo "BASE_URL=$BASE_URL" >> .env 
          echo ".env file created with the following content:"
          cat .env

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Analyze code
        script: |
          flutter analyze

      - name: Run tests
        script: |
          flutter test

      - name: Build AAB
        script: |
          flutter build aab --release

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/bundle/**
      - build/app/outputs/flutter-apk/**

    publishing:
      email:
        recipients:
          - ithoriq0@gmail.com
      scripts:
        - name: Print path to AAB and APK
          script: |
            echo "Your AAB file is located at: $(ls build/app/outputs/bundle/release/*.aab)"
            echo "Your APK file is located at: $(ls build/app/outputs/flutter-apk/*.apk)"
